# docker-compose.yml

version: "3"

services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
    expose:
      - 5432:5432
volumes:
  db:
    driver: local
